### PR TITLE
update of inputs to respect the design of Contentful

### PR DESCRIPTION
**Pull request by max8392**

### CODE REVIEW

**Review by pauloamgomes — CHANGES_REQUESTED** [review]
The reset button position needs to be also updated, otherwise will look like:

image

its just a minor adjustment on the top and right position, maybe 7px for both

**Comment by max8392** [comment]
To respect the design of Contentful, I would display it as below

image

Si vous êtes d'accord ;-) sinon je réglé juste simplement le bouton

**Comment by max8392** [comment]
I've push correction with the reset button center ;-)

**Comment by pauloamgomes** [comment]
thanks

**Pull request merged**
